[server]
port = 8501
headless = false
runOnSave = true
folderWatchBlacklist = [".scrapy"]

[client]
toolbarMode = "minimal"

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[ui]
hideTopBar = true

# Eigene Einstellungen kannst du unterhalb dieser Zeile einfügen.

[theme]
base="light"
primaryColor="DarkRed"
backgroundColor="OldLace"
secondaryBackgroundColor="Moccasin"
textColor="Black"
font="serif"
