[server]
port = 8080
headless = false
runOnSave = true
folderWatchBlacklist = [".scrapy"]

[client]
toolbarMode = "minimal"

[browser]
serverAddress = "localhost"
serverPort = 8080
gatherUsageStats = false

[ui]
hideTopBar = true

# Eigene Einstellungen kannst du unterhalb dieser Zeile einfügen.
